### ISSUE TITLE
doc: attach note for deprecations

### ISSUE THREAD

**Issue by jsha** [rustls/webpki#148]
I noticed at https://docs.rs/rustls-webpki/latest/webpki/struct.TlsClientTrustAnchors.html that the type and its field are marked with `#[deprecated(since = "0.101.2")]`. There's an additional parameter to the `deprecated` attribute, called `note`:

https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute

> note — Specifies a string that should be included in the deprecation message. This is typically used to provide an explanation about the deprecation and preferred alternatives.

It would be useful to attach a note to this deprecation (and others that don't have notes) explaining why it was deprecated and what to use instead.

**Comment by cpu** [comment]
Thanks for pointing out that oversight. There were only two deprecations missing a note, but I think we could do a better job across the board on providing context for the changes. 

Since the deprecated content is already removed in `main` we'll need a maintenance release to fix this up, I started one with updated `note`'s in https://github.com/rustls/webpki/pull/149

**Comment by djc** [comment]
Just to connect the dots here, the offending changes here are from my PR #133.

**Comment by cpu** [comment]
This was resolved with https://github.com/rustls/webpki/pull/149 and the published v0.101.3 release. Thanks!
